# Generated by Django 5.2.12 on 2026-05-24 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_availableslot_booking_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='reading_type',
            field=models.CharField(choices=[('Three Card', 'Three Card'), ('Celtic Cross', 'Celtic Cross'), ('Love Reading', 'Love Reading'), ('Career Path', 'Career Path'), ('Year Ahead', 'Year Ahead'), ('Full Spread', 'Full Spread'), ('Numerology', 'Numerology'), ('Lal Kitab', 'Lal Kitab'), ('Vastu', 'Vastu')], max_length=100),
        ),
    ]
