# Generated by Django 5.2.14 on 2026-05-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_booking_date_time_optional'),
        ('readings', '0004_delete_reading_alter_availableslot_id_and_more'),
    ]

    operations = [
    ]
